package com.vrcx.android.data.db.dao

import com.vrcx.android.data.db.accountScopedKey
import com.vrcx.android.data.db.entityIdFromScopedKey
import com.vrcx.android.data.db.entity.FriendNotifyEntity
import com.vrcx.android.data.db.entity.MemoEntity
import com.vrcx.android.data.db.entity.NoteEntity

/**
 * `(ownerId, userId)`-keyed accessors that own the `ownerUserId:userId` composite
 * key so no ViewModel or repository has to assemble or parse it by hand. Each
 * delegates to the raw composite-key DAO queries generated by Room.
 */

// --- MemoDao ---

suspend fun MemoDao.getMemo(ownerId: String, userId: String): MemoEntity? =
    getMemo(accountScopedKey(ownerId, userId))

suspend fun MemoDao.saveMemo(ownerId: String, userId: String, memo: String, editedAt: String) =
    insertMemo(
        MemoEntity(
            odUserId = accountScopedKey(ownerId, userId),
            ownerUserId = ownerId,
            editedAt = editedAt,
            memo = memo,
        )
    )

/** All of [ownerId]'s memos keyed by the target userId. */
suspend fun MemoDao.memosByUserId(ownerId: String): Map<String, String> =
    getMemos(ownerId).associate { it.odUserId.entityIdFromScopedKey() to it.memo }

// --- NoteDao ---

suspend fun NoteDao.getNote(ownerId: String, userId: String): NoteEntity? =
    get(accountScopedKey(ownerId, userId))

suspend fun NoteDao.save(
    ownerId: String,
    userId: String,
    displayName: String,
    note: String,
    createdAt: String,
) {
    val key = accountScopedKey(ownerId, userId)
    insert(
        NoteEntity(
            compositeId = key,
            ownerUserId = ownerId,
            odUserId = key,
            displayName = displayName,
            note = note,
            createdAt = createdAt,
        )
    )
}

// --- FriendNotifyDao ---

suspend fun FriendNotifyDao.isEnabled(ownerId: String, userId: String): Boolean =
    get(accountScopedKey(ownerId, userId)) != null

suspend fun FriendNotifyDao.enable(ownerId: String, userId: String) =
    insert(
        FriendNotifyEntity(
            compositeId = accountScopedKey(ownerId, userId),
            ownerUserId = ownerId,
            friendUserId = userId,
        )
    )

suspend fun FriendNotifyDao.disable(ownerId: String, userId: String) =
    delete(accountScopedKey(ownerId, userId))
