package com.vrcx.android.ui.theme

import androidx.compose.ui.graphics.Color

// VRChat trust rank colors
val TrustVisitor = Color(0xFFCCCCCC)
val TrustNewUser = Color(0xFF1778FF)
val TrustUser = Color(0xFF2BCF5C)
val TrustKnownUser = Color(0xFFFF7B42)
val TrustTrustedUser = Color(0xFF8143E6)
val TrustFriend = Color(0xFFFFFF00)

// VRChat status colors
val StatusOnline = Color(0xFF51E57C)
val StatusJoinMe = Color(0xFF42CAFF)
val StatusAskMe = Color(0xFFE88134)
val StatusBusy = Color(0xFFCB3E3E)
val StatusOffline = Color(0xFF808080)

// Desktop-inspired accent and neutrals.
val VrcxAccentBlue = Color(0xFF1447E6)
val VrcxAccentBlueSoft = Color(0xFFEFF6FF)
val VrcxAccentBlueDeep = Color(0xFF0A0A0A)

// --- Dark theme colors ---
val VrcxDarkPrimary = Color(0xFFFAFAFA)
val VrcxDarkOnPrimary = Color(0xFF171717)
val VrcxDarkPrimaryContainer = Color(0xFF262626)
val VrcxDarkOnPrimaryContainer = Color(0xFFFAFAFA)
val VrcxDarkSecondary = Color(0xFF262626)
val VrcxDarkOnSecondary = Color(0xFFFAFAFA)
val VrcxDarkSecondaryContainer = Color(0xFF262626)
val VrcxDarkOnSecondaryContainer = Color(0xFFFAFAFA)
val VrcxDarkTertiary = VrcxAccentBlue
val VrcxDarkOnTertiary = Color(0xFFEFF6FF)
val VrcxDarkTertiaryContainer = Color(0xFF262626)
val VrcxDarkOnTertiaryContainer = Color(0xFFFAFAFA)
val VrcxDarkBackground = Color(0xFF0A0A0A)
val VrcxDarkOnBackground = Color(0xFFFAFAFA)
val VrcxDarkSurface = Color(0xFF0A0A0A)
val VrcxDarkOnSurface = Color(0xFFFAFAFA)
val VrcxDarkSurfaceVariant = Color(0xFF262626)
val VrcxDarkOnSurfaceVariant = Color(0xFFA1A1A1)
val VrcxDarkSurfaceContainerLowest = Color(0xFF0A0A0A)
val VrcxDarkSurfaceContainerLow = Color(0xFF0A0A0A)
val VrcxDarkSurfaceContainer = Color(0xFF0A0A0A)
val VrcxDarkSurfaceContainerHigh = Color(0xFF262626)
val VrcxDarkSurfaceContainerHighest = Color(0xFF262626)
val VrcxDarkOutline = Color(0xFF262626)
val VrcxDarkOutlineVariant = Color(0xFF262626)
val VrcxDarkRing = Color(0xFF525252)
val VrcxDarkError = Color(0xFF82181A)
val VrcxDarkOnError = Color(0xFFFB2C36)
val VrcxDarkErrorContainer = Color(0xFF262626)
val VrcxDarkOnErrorContainer = Color(0xFFFB2C36)
val VrcxDarkInverseSurface = Color(0xFFFAFAFA)
val VrcxDarkInverseOnSurface = Color(0xFF171717)
val VrcxDarkInversePrimary = Color(0xFF171717)

// --- Light theme colors ---
val VrcxLightPrimary = Color(0xFF2563EB)
val VrcxLightOnPrimary = Color(0xFFFFFFFF)
val VrcxLightPrimaryContainer = Color(0xFFDCE8FF)
val VrcxLightOnPrimaryContainer = Color(0xFF0B2C68)
val VrcxLightSecondary = Color(0xFF425062)
val VrcxLightOnSecondary = Color(0xFFFFFFFF)
val VrcxLightSecondaryContainer = Color(0xFFE6ECF4)
val VrcxLightOnSecondaryContainer = Color(0xFF1E2938)
val VrcxLightTertiary = Color(0xFF0F766E)
val VrcxLightOnTertiary = Color(0xFFFFFFFF)
val VrcxLightTertiaryContainer = Color(0xFFD0F3EC)
val VrcxLightOnTertiaryContainer = Color(0xFF0B3B36)
val VrcxLightBackground = Color(0xFFF3F5F8)
val VrcxLightOnBackground = Color(0xFF171C23)
val VrcxLightSurface = Color(0xFFFAFBFD)
val VrcxLightOnSurface = Color(0xFF171C23)
val VrcxLightSurfaceVariant = Color(0xFFE7EBF0)
val VrcxLightOnSurfaceVariant = Color(0xFF556071)
val VrcxLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val VrcxLightSurfaceContainerLow = Color(0xFFF8FAFC)
val VrcxLightSurfaceContainer = Color(0xFFF1F4F8)
val VrcxLightSurfaceContainerHigh = Color(0xFFEBEFF5)
val VrcxLightSurfaceContainerHighest = Color(0xFFE3E9F1)
val VrcxLightOutline = Color(0xFFBBC5D2)
val VrcxLightOutlineVariant = Color(0xFFD7DEE7)
val VrcxLightRing = Color(0xFFB3BCC9)
val VrcxLightError = Color(0xFFC62828)
val VrcxLightOnError = Color(0xFFFFFFFF)
val VrcxLightErrorContainer = Color(0xFFFFE1DE)
val VrcxLightOnErrorContainer = Color(0xFF5A1414)
val VrcxLightInverseSurface = Color(0xFF1B2230)
val VrcxLightInverseOnSurface = Color(0xFFF5F7FA)
val VrcxLightInversePrimary = Color(0xFF8AB2FF)

// Semantic colors
val VrcxSuccess = Color(0xFF4CAF50)
val VrcxWarning = Color(0xFFFFA726)
val VrcxInfo = Color(0xFF42A5F5)

// Anthropic brand colors
val AnthropicDark = Color(0xFF141413)
val AnthropicLight = Color(0xFFFAF9F5)
val AnthropicMidGray = Color(0xFFB0AEA5)
val AnthropicOrange = Color(0xFFD97757)
