package com.vrcx.android.ui.theme

import androidx.compose.ui.graphics.Color

// VRChat trust rank colors
val TrustVisitor = Color(0xFFCCCCCC)
val TrustNewUser = Color(0xFF1778FF)
val TrustUser = Color(0xFF2BCF5C)
val TrustKnownUser = Color(0xFFFF7B42)
val TrustTrustedUser = Color(0xFF8143E6)
val TrustFriend = Color(0xFFFFFF00)

// VRChat status colors
val StatusOnline = Color(0xFF51E57C)
val StatusJoinMe = Color(0xFF42CAFF)
val StatusAskMe = Color(0xFFE88134)
val StatusBusy = Color(0xFFCB3E3E)
val StatusOffline = Color(0xFF808080)

// --- Dark theme colors ---
val VrcxDarkPrimary = Color(0xFFB8A1FF)
val VrcxDarkOnPrimary = Color(0xFF2D1A6E)
val VrcxDarkPrimaryContainer = Color(0xFF3D2D80)
val VrcxDarkOnPrimaryContainer = Color(0xFFE2D9FF)
val VrcxDarkSecondary = Color(0xFF7DD6E8)
val VrcxDarkOnSecondary = Color(0xFF003D47)
val VrcxDarkSecondaryContainer = Color(0xFF1A4D58)
val VrcxDarkOnSecondaryContainer = Color(0xFFBEEDF7)
val VrcxDarkTertiary = Color(0xFFE0A0C0)
val VrcxDarkOnTertiary = Color(0xFF4A1A35)
val VrcxDarkTertiaryContainer = Color(0xFF5E2D4A)
val VrcxDarkOnTertiaryContainer = Color(0xFFF5D0E5)
val VrcxDarkBackground = Color(0xFF0F0F1A)
val VrcxDarkOnBackground = Color(0xFFE6E1F0)
val VrcxDarkSurface = Color(0xFF141420)
val VrcxDarkOnSurface = Color(0xFFE6E1F0)
val VrcxDarkSurfaceVariant = Color(0xFF2A2A3C)
val VrcxDarkOnSurfaceVariant = Color(0xFFCBC4D6)
val VrcxDarkSurfaceContainerLowest = Color(0xFF0B0B14)
val VrcxDarkSurfaceContainerLow = Color(0xFF1A1A2E)
val VrcxDarkSurfaceContainer = Color(0xFF1F1F33)
val VrcxDarkSurfaceContainerHigh = Color(0xFF252540)
val VrcxDarkSurfaceContainerHighest = Color(0xFF2E2E4A)
val VrcxDarkOutline = Color(0xFF504A5C)
val VrcxDarkOutlineVariant = Color(0xFF3A3648)
val VrcxDarkError = Color(0xFFFFB4AB)
val VrcxDarkOnError = Color(0xFF690005)
val VrcxDarkErrorContainer = Color(0xFF8C1D18)
val VrcxDarkOnErrorContainer = Color(0xFFFFDAD6)
val VrcxDarkInverseSurface = Color(0xFFE6E1F0)
val VrcxDarkInverseOnSurface = Color(0xFF1A1A2E)
val VrcxDarkInversePrimary = Color(0xFF5A3DBF)

// --- Light theme colors ---
val VrcxLightPrimary = Color(0xFF5A3DBF)
val VrcxLightOnPrimary = Color(0xFFFFFFFF)
val VrcxLightPrimaryContainer = Color(0xFFE2D9FF)
val VrcxLightOnPrimaryContainer = Color(0xFF1A0050)
val VrcxLightSecondary = Color(0xFF006878)
val VrcxLightOnSecondary = Color(0xFFFFFFFF)
val VrcxLightSecondaryContainer = Color(0xFFBEEDF7)
val VrcxLightOnSecondaryContainer = Color(0xFF001F26)
val VrcxLightTertiary = Color(0xFF7A4063)
val VrcxLightOnTertiary = Color(0xFFFFFFFF)
val VrcxLightTertiaryContainer = Color(0xFFF5D0E5)
val VrcxLightOnTertiaryContainer = Color(0xFF30001F)
val VrcxLightBackground = Color(0xFFFCF8FF)
val VrcxLightOnBackground = Color(0xFF1C1B22)
val VrcxLightSurface = Color(0xFFFCF8FF)
val VrcxLightOnSurface = Color(0xFF1C1B22)
val VrcxLightSurfaceVariant = Color(0xFFE7E0F0)
val VrcxLightOnSurfaceVariant = Color(0xFF49454F)
val VrcxLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val VrcxLightSurfaceContainerLow = Color(0xFFF7F2FC)
val VrcxLightSurfaceContainer = Color(0xFFF1ECF6)
val VrcxLightSurfaceContainerHigh = Color(0xFFEBE6F0)
val VrcxLightSurfaceContainerHighest = Color(0xFFE5E1EB)
val VrcxLightOutline = Color(0xFF7A757F)
val VrcxLightOutlineVariant = Color(0xFFCBC4D6)
val VrcxLightError = Color(0xFFBA1A1A)
val VrcxLightOnError = Color(0xFFFFFFFF)
val VrcxLightErrorContainer = Color(0xFFFFDAD6)
val VrcxLightOnErrorContainer = Color(0xFF410002)
val VrcxLightInverseSurface = Color(0xFF313038)
val VrcxLightInverseOnSurface = Color(0xFFF4EFF9)
val VrcxLightInversePrimary = Color(0xFFB8A1FF)

// Semantic colors
val VrcxSuccess = Color(0xFF4CAF50)
val VrcxWarning = Color(0xFFFFA726)
val VrcxInfo = Color(0xFF42A5F5)

// Anthropic brand colors
val AnthropicDark = Color(0xFF141413)
val AnthropicLight = Color(0xFFFAF9F5)
val AnthropicMidGray = Color(0xFFB0AEA5)
val AnthropicOrange = Color(0xFFD97757)
